### ISSUE TITLE
Disallow cyrillic characters in variable name

### ISSUE THREAD

**Issue by pustovalov** [chejen/eslint-plugin-i18n#12]
Hey,

```
var кириллица = 1

кириллица
1
```

example:
`var moсkResponse` - `с` is cyrillic

`i18n/no-russian-character` - does not track such use, is this expected behaviour?

**Comment by chejen** [comment]
Yep, it's expected since we only care about the *String* values. After all, we don't internationalize variables, right?

**Comment by pustovalov** [comment]
Right, maybe the way I use the plugin is not very consistent with its main purpose

my use case is: disallow any cyrillic characters in code, WDYT about to create such a set of rules?

**Comment by chejen** [comment]
I'll see what I can do.

**Comment by chejen** [comment]
@pustovalov, I've made some updates, could you test it to see if it meets your requirements.

1. Switch `eslint-plugin-i18n` in your package.json to `chejen/eslint-plugin-i18n#develop`:
```json
  "devDependencies": {
    "eslint-plugin-i18n": "chejen/eslint-plugin-i18n#develop"
  },
```

2. Follow the [Rule Options](https://github.com/chejen/eslint-plugin-i18n/blob/develop/docs/rules/no-russian-character.md#rule-options) section in documentation to set your rules.
3. Check out if it works.

Let me know if it helps, thanks.

**Comment by pustovalov** [comment]
@chejen I have checked, works perfectly

**Comment by chejen** [comment]
The new version has released, enjoy it.
