### ISSUE TITLE
Feature Request: exclude support member expression

### ISSUE THREAD

**Issue by adrien-LD** [chejen/eslint-plugin-i18n#23]
There are cases where i18n dictionary keys are managed in Chinese.
```
{
  "保存": "保存",
  "确定": "确定",
   ...
}
```
And the i18n function may exist in many forms, such as the following:
```
const a = i18n.t('保存');
```
In this case, even though I configured in the `.eslintrc` file:
```
"i18n/no-chinese-character": ["error", {
   "excludeArgsForFunctions": ["i18n.t"]
  }]
```
But it still reports an error
```
const a = i18n.t('保存'); // Using Chinese characters: '保存'
```
It would be best if `excludeArgsForFunctions` could support functions in the form of `i18n.t`

**Comment by chejen** [comment]
Close it since #24 has been merged.

@adrien-LD Please let me know if it works or if there's anything we'd like to adjust. Thanks!
