### ISSUE TITLE
Add `ignoreImport` Option to Ignore Import Statements in Rule

### ISSUE THREAD

**Issue by moonou** [chejen/eslint-plugin-i18n#26]
Hello,

Thank you for developing this great ESLint plugin! I have been using it and found it very useful. However, I came across a scenario where I needed to ignore import statements from being flagged by the rule.

To handle this in my own project, I use PNPM patch to add code to skip import declarations when processing Literal, TemplateElement, and other relevant nodes. This worked for my case, but I believe it would be beneficial for other users as well to have an option to ignore import statements built into the plugin.

I would like to suggest adding a new option, such as `ignoreImport`, when set to true, would prevent the rule from checking any import statement content.

**Comment by chejen** [comment]
@moonou Could you share some sample code for reference?

**Comment by moonou** [comment]
> @moonou Could you share some sample code for reference?
Here’s your updated description in English with some improvements for clarity and grammar:

In my workflow, I use [orval](https://orval.dev/) to generate TypeScript code directly from OpenAPI JSON files. Since our team is based in China, the backend team typically defines module names in Chinese. After generating the code, the structure looks like this:
```
modules
  模块A
     api.ts
  模块B
     api.ts
```

When the frontend imports the code, it appears like this:
``` typescript
import { doSomething } from '模块A/api';
```

This causes issues when I use a linting plugin, as it flags the code. To address this, I modified the plugin to ignore import syntax, making the following patch:
``` diff
'Literal, JSXText': function(node) {
+   if (node.parent.type === 'ImportDeclaration') {
+     return;
+   }

   if (typeof excludeArgsForFunctions === 'object') {
     if (node.parent.type === 'CallExpression' && excludeArgsForFunctions.some((value) => isExcludeFunction(node, value))) {
       return;
   }
 },
 'TemplateElement': function(node) {
+   if (node.parent.parent.type === 'ImportDeclaration') {
+     return;
+   }
```

**Comment by chejen** [comment]
@moonou Can you test this [pre-release version (2.4.0-rc.1)](https://www.npmjs.com/package/eslint-plugin-i18n/v/2.4.0-rc.1) when you have time?

For the usage, please refer to [the doc](https://github.com/chejen/eslint-plugin-i18n/blob/feature/exclude-module-imports/docs/rules/no-chinese-character.md#boolean-excludemoduleimports). Kindly let me know if it works. Thanks.

**Comment by moonou** [comment]
@chejen Thank you for your work! I’m using version `2.4.0-rc.1` and added `excludeModuleImports` to my project. It works great!

**Comment by chejen** [comment]
v2.4.0 has rolled out. Enjoy it.
